[project]
name = "douyu-mcp-py"
version = "0.1.0"
description = "一个查询斗鱼直播间信息的mcp server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.3",
    "requests>=2.32.4",
]
